server:
  port: 8088

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.97.105.45:3306/question_management?characterEncoding=UTF-8&useUnicode=true&serverTimezone=UTC
#    url: jdbc:mysql:/rm-bp1nl7p8y9fc8x2xqmo.mysql.rds.aliyuncs.com:3306/weixin?characterEncoding=UTF-8&useUnicode=true
    username: root
#    username: zjzy_test
    password: cjnroot
#    password: Zoomlgd89921110@2019
    tomcat-jdbc: com.alibaba.datasource.pool.DruidDataSource
    initial-size: 20                      #初始化连接数量
    minIdle: 5                            #最小连接池数量
    maxActive: 20                         #最大连接数量
    maxWait: 10000                        #获取连接最大等待时间，毫秒
    timeBetweenEvictionRunsMillis: 60000  #多久进行一次检测，关闭空闲连接，毫秒
    minEvictableIdleTimeMillis: 300000    #一个连接在池中的最小生存时间，毫秒
    testWhileIdle: true                   #是否在空闲时测试连接，配置为true，以保证安全
    testOnBorrow: true                    #获取连接时是否执行检测，配置为true，以保证连接可用
    testOnReturn: false                   #返回连接时是否检测，这里选择关闭，提高性能
    poolPreparedStatements: false         #是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
    maxPoolPreparedStatementPerConnectionSize: 20   #每个连接上的PSCache的个数
    validationQuery: select 1             #验证连接有效与否的SQL
    filters: stat,log4j,wall
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
                                          #通过connectProperties属性来打开mergeSql功能；慢SQL记录
    useGlobalDataSourceStat: true         #合并多个DruidDataSource的监控数据
    
  output: 
    ansi: 
      enabled: always
    
  jpa:
    show-sql: true             #显示SQL语句
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: false               #关闭缓存以查询最新页面
    mode: LEGACYHTML5          #非完全检查，严格使用HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html

logging:
  config: classpath:logback-spring.xml
  path: D:/QuestionManagement/logs/
  level:
    root: INFO
    console: info
logging.level.org.springframework.boot.autoconfigure: ERROR


